In [26]:
import numpy as np
from utils import fitPlotter, Zscore, texTabler, mytestZ
import import_ipynb
import gamma
from scipy import stats

In [27]:
energyNa22   = 0.5110
energyNa22_2  = 1.2745
energyCo60_1 = 1.1732
energyCo60_2 = 1.3325
energyCs137  = 0.66166

errenergyNa22   = 0.001
errenergyNa22_2 = 0.0001
errenergyCo60_1 = 0.001
errenergyCo60_2 = 0.001
errenergyCs137  = 0.0001

In [34]:
Eg = np.array([energyNa22, energyNa22_2, energyCo60_1, energyCs137]) # MeV
ErrEg = np.array([errenergyNa22, errenergyNa22_2, errenergyCo60_1, errenergyCs137])

SpExp = np.array([208, 628,570, 287])
errSpExp = np.array([16,30, 24, 16])
chSp = np.array([i for i in zip(SpExp,errSpExp)])
E_Sp, errE_Sp = gamma.calibration(chSp[:,0], chSp[:,1])
E_Sp, errE_Sp

(array([0.34031132, 1.06835185, 0.96704719, 0.4762698 ]),
 array([0.02815215, 0.05518227, 0.04453785, 0.02861763]))

In [35]:
Esp = np.array([i for i in zip(E_Sp,errE_Sp)])

me = 0.511 # MeV
SpTh = Eg * ((Eg/me) / (0.5 + Eg/me))
ErrSpTh = (ErrEg / Eg) * SpTh

E = np.array([i for i in zip(SpTh, ErrSpTh)])

Zscore(Esp,E)
#texTabler([E_Sp, SpTh, Zscore(Esp,E)],[errE_Sp, ErrSpTh, np.ones(len(E))*0.001 ],["E_{\text{sp, exp}}", "E_{\text{sp, th}", "Z_\text{score}"])
p_v = 2 * (1 - stats.norm.cdf(abs(Zscore(Esp,E))))
p_v

z value of param 0 : 0.0126
z value of param 1 : -0.121
z value of param 2 : -0.0821
z value of param 3 : 0.0373


z value of param 0 : 0.0126
z value of param 1 : -0.121
z value of param 2 : -0.0821
z value of param 3 : 0.0373




array([0.98993187, 0.9035768 , 0.93460382, 0.97026617])

In [31]:
Eg = np.array([energyNa22, energyCo60_1, energyCo60_2, energyCs137]) # MeV
ErrEg = np.array([errenergyNa22, errenergyCo60_1, errenergyCo60_2, errenergyCs137])
chB = np.array([106,131,131,116])
echB = np.array([11,16,16,12])
Back, eBack = gamma.calibration(chB, echB)
me = 0.511 # MeV
SpTh = Eg * ((Eg/me) / (0.5 + Eg/me))
ErrSpTh = (ErrEg / Eg) * SpTh
BackTh = Eg - SpTh
ErrBackTh = (ErrEg / Eg) * BackTh
B = np.array([i for i in zip(Back,eBack)])
TB = np.array([i for i in zip(BackTh,ErrBackTh)])
Zscore(B,TB)
p_v = 2 * (1 - stats.norm.cdf(abs(Zscore(B,TB))))
p_v

z value of param 0 : 0.253
z value of param 1 : 0.0566
z value of param 2 : 0.221
z value of param 3 : 0.084


z value of param 0 : 0.253
z value of param 1 : 0.0566
z value of param 2 : 0.221
z value of param 3 : 0.084




array([0.80061599, 0.95486454, 0.82484934, 0.93302899])

In [25]:
texTabler([Back,BackTh,Zscore(B,TB)],[eBack,ErrBackTh,np.zeros(len(BackTh))],["E_SPERR", "E_TEORR", "Zscore"])

z value of param 0 : 0.253
z value of param 1 : 0.0566
z value of param 2 : 0.221
z value of param 3 : 0.084


$E_SPERR$ & $\delta E_SPERR$ & $E_TEORR$ & $\delta E_TEORR$ & $Zscore$ & $\delta Zscore$ \\\\
\hline
0.165 & 0.019 & 0.1703 & 0.0003 & 0.3 & 0.0\\
0.21 & 0.03 & 0.20981 & 0.00018 & 0.1 & 0.0\\
0.21 & 0.03 & 0.21439 & 0.00016 & 0.2 & 0.0\\
0.18 & 0.02 & 0.18432 & 0.00003 & 0.1 & 0.0\\


### $K_{\alpha}$

In [12]:
xNa22  = 48.89
xCo60  = 48.26
xCs137 = 50.12

errxNa22  = 1.54
errxCo60  = 1.54
errxCs137 = 1.54

xTh    = 0.074 # valore teorico in MeV
errxTh = 0.001

X, eX = gamma.calibration(np.array([xNa22,xCo60,xCs137]),np.array([errxNa22,errxCo60,errxCs137]))
EX = np.array([i for i in zip(X, eX)])
Zscore(EX, np.array([[xTh,errxTh] for i in range(3)]))

z value of param 0 : 1.24
z value of param 1 : 1.46
z value of param 2 : 0.817




array([1.24274631, 1.46143266, 0.81651386])

In [13]:
eX

array([0.00483368, 0.00483064, 0.00483974])